/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(Config, Config, AUTO)


PB_BIND(Frame, Frame, 2)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(ClientPacket, ClientPacket, AUTO)


PB_BIND(ClientInfo, ClientInfo, AUTO)


PB_BIND(RemoteLog, RemoteLog, AUTO)





