/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(WFrame, WFrame, 2)


PB_BIND(RGBFrame, RGBFrame, 2)


PB_BIND(AudioFrame, AudioFrame, AUTO)


PB_BIND(SynthAdsrConfig, SynthAdsrConfig, AUTO)


PB_BIND(SynthReverbConfig, SynthReverbConfig, AUTO)


PB_BIND(SynthConfig, SynthConfig, AUTO)


PB_BIND(SynthFrame, SynthFrame, AUTO)


PB_BIND(InputLightEvent, InputLightEvent, AUTO)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(ControlEvent, ControlEvent, AUTO)


PB_BIND(SoundToLightControlEvent, SoundToLightControlEvent, AUTO)


PB_BIND(ProximityEvent, ProximityEvent, AUTO)


PB_BIND(FirmwareConfig, FirmwareConfig, AUTO)


PB_BIND(FirmwarePacket, FirmwarePacket, AUTO)


PB_BIND(FirmwareInfo, FirmwareInfo, AUTO)


PB_BIND(RemoteLog, RemoteLog, AUTO)















