/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SCHEMA_PB_H_INCLUDED
#define PB_SCHEMA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _EasingMode {
    EasingMode_LINEAR = 0,
    EasingMode_EASE_IN_QUAD = 1,
    EasingMode_EASE_OUT_QUAD = 2,
    EasingMode_EASE_IN_OUT_QUAD = 3,
    EasingMode_EASE_IN_CUBIC = 4,
    EasingMode_EASE_OUT_CUBIC = 5,
    EasingMode_EASE_IN_OUT_CUBIC = 6,
    EasingMode_EASE_IN_QUART = 7,
    EasingMode_EASE_OUT_QUART = 8,
    EasingMode_EASE_IN_OUT_QUART = 9,
    EasingMode_EASE_IN_QUINT = 10,
    EasingMode_EASE_OUT_QUINT = 11,
    EasingMode_EASE_IN_OUT_QUINT = 12,
    EasingMode_EASE_IN_EXPO = 13,
    EasingMode_EASE_OUT_EXPO = 14,
    EasingMode_EASE_IN_OUT_EXPO = 15
} EasingMode;

typedef enum _EventType {
    EventType_BUTTON = 0,
    EventType_DIRECTION = 1
} EventType;

/* Struct definitions */
typedef struct _Config {
    uint32_t luminance;
    uint32_t easing_interval_ms;
    EasingMode easing_mode;
    bool show_test_frame;
    uint32_t config_phash;
    bool enable_calibration;
} Config;

typedef PB_BYTES_ARRAY_T(640) Frame_data_t;
typedef PB_BYTES_ARRAY_T(256) Frame_palette_t;
typedef struct _Frame {
    Frame_data_t data; /* Selects pixel colors from the palette. First pixel is top left. */
    Frame_palette_t palette; /* Series of RGB values. 8bit per color. */
} Frame;

typedef struct _Packet {
    pb_size_t which_content;
    union {
        Config config;
        Frame frame;
    } content;
} Packet;

typedef struct _InputEvent {
    EventType type;
    uint32_t value;
} InputEvent;

typedef struct _ClientInfo {
    char hostname[21];
    char build_time[21];
    uint32_t panel_index;
    uint32_t fps;
    uint32_t config_phash;
} ClientInfo;

typedef struct _RemoteLog {
    char message[101];
} RemoteLog;

typedef struct _ClientPacket {
    pb_size_t which_content;
    union {
        ClientInfo client_info;
        RemoteLog remote_log;
    } content;
} ClientPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _EasingMode_MIN EasingMode_LINEAR
#define _EasingMode_MAX EasingMode_EASE_IN_OUT_EXPO
#define _EasingMode_ARRAYSIZE ((EasingMode)(EasingMode_EASE_IN_OUT_EXPO+1))

#define _EventType_MIN EventType_BUTTON
#define _EventType_MAX EventType_DIRECTION
#define _EventType_ARRAYSIZE ((EventType)(EventType_DIRECTION+1))


#define Config_easing_mode_ENUMTYPE EasingMode


#define InputEvent_type_ENUMTYPE EventType





/* Initializer values for message structs */
#define Packet_init_default                      {0, {Config_init_default}}
#define Config_init_default                      {0, 0, _EasingMode_MIN, 0, 0, 0}
#define Frame_init_default                       {{0, {0}}, {0, {0}}}
#define InputEvent_init_default                  {_EventType_MIN, 0}
#define ClientPacket_init_default                {0, {ClientInfo_init_default}}
#define ClientInfo_init_default                  {"", "", 0, 0, 0}
#define RemoteLog_init_default                   {""}
#define Packet_init_zero                         {0, {Config_init_zero}}
#define Config_init_zero                         {0, 0, _EasingMode_MIN, 0, 0, 0}
#define Frame_init_zero                          {{0, {0}}, {0, {0}}}
#define InputEvent_init_zero                     {_EventType_MIN, 0}
#define ClientPacket_init_zero                   {0, {ClientInfo_init_zero}}
#define ClientInfo_init_zero                     {"", "", 0, 0, 0}
#define RemoteLog_init_zero                      {""}

/* Field tags (for use in manual encoding/decoding) */
#define Config_luminance_tag                     1
#define Config_easing_interval_ms_tag            2
#define Config_easing_mode_tag                   3
#define Config_show_test_frame_tag               4
#define Config_config_phash_tag                  5
#define Config_enable_calibration_tag            6
#define Frame_data_tag                           1
#define Frame_palette_tag                        2
#define Packet_config_tag                        1
#define Packet_frame_tag                         2
#define InputEvent_type_tag                      1
#define InputEvent_value_tag                     2
#define ClientInfo_hostname_tag                  1
#define ClientInfo_build_time_tag                2
#define ClientInfo_panel_index_tag               3
#define ClientInfo_fps_tag                       4
#define ClientInfo_config_phash_tag              5
#define RemoteLog_message_tag                    1
#define ClientPacket_client_info_tag             1
#define ClientPacket_remote_log_tag              2

/* Struct field encoding specification for nanopb */
#define Packet_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,config,content.config),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,frame,content.frame),   2)
#define Packet_CALLBACK NULL
#define Packet_DEFAULT NULL
#define Packet_content_config_MSGTYPE Config
#define Packet_content_frame_MSGTYPE Frame

#define Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   luminance,         1) \
X(a, STATIC,   SINGULAR, UINT32,   easing_interval_ms,   2) \
X(a, STATIC,   SINGULAR, UENUM,    easing_mode,       3) \
X(a, STATIC,   SINGULAR, BOOL,     show_test_frame,   4) \
X(a, STATIC,   SINGULAR, UINT32,   config_phash,      5) \
X(a, STATIC,   SINGULAR, BOOL,     enable_calibration,   6)
#define Config_CALLBACK NULL
#define Config_DEFAULT NULL

#define Frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, BYTES,    palette,           2)
#define Frame_CALLBACK NULL
#define Frame_DEFAULT NULL

#define InputEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define InputEvent_CALLBACK NULL
#define InputEvent_DEFAULT NULL

#define ClientPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,client_info,content.client_info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,remote_log,content.remote_log),   2)
#define ClientPacket_CALLBACK NULL
#define ClientPacket_DEFAULT NULL
#define ClientPacket_content_client_info_MSGTYPE ClientInfo
#define ClientPacket_content_remote_log_MSGTYPE RemoteLog

#define ClientInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   SINGULAR, STRING,   build_time,        2) \
X(a, STATIC,   SINGULAR, UINT32,   panel_index,       3) \
X(a, STATIC,   SINGULAR, UINT32,   fps,               4) \
X(a, STATIC,   SINGULAR, UINT32,   config_phash,      5)
#define ClientInfo_CALLBACK NULL
#define ClientInfo_DEFAULT NULL

#define RemoteLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define RemoteLog_CALLBACK NULL
#define RemoteLog_DEFAULT NULL

extern const pb_msgdesc_t Packet_msg;
extern const pb_msgdesc_t Config_msg;
extern const pb_msgdesc_t Frame_msg;
extern const pb_msgdesc_t InputEvent_msg;
extern const pb_msgdesc_t ClientPacket_msg;
extern const pb_msgdesc_t ClientInfo_msg;
extern const pb_msgdesc_t RemoteLog_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Packet_fields &Packet_msg
#define Config_fields &Config_msg
#define Frame_fields &Frame_msg
#define InputEvent_fields &InputEvent_msg
#define ClientPacket_fields &ClientPacket_msg
#define ClientInfo_fields &ClientInfo_msg
#define RemoteLog_fields &RemoteLog_msg

/* Maximum encoded size of messages (where known) */
#define ClientInfo_size                          62
#define ClientPacket_size                        104
#define Config_size                              24
#define Frame_size                               902
#define InputEvent_size                          8
#define Packet_size                              905
#define RemoteLog_size                           102

#ifdef __cplusplus
} /* extern "C" */
#endif

#ifdef __cplusplus
/* Message descriptors for nanopb */
namespace nanopb {
template <>
struct MessageDescriptor<Packet> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &Packet_msg;
    }
};
template <>
struct MessageDescriptor<Config> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 6;
    static inline const pb_msgdesc_t* fields() {
        return &Config_msg;
    }
};
template <>
struct MessageDescriptor<Frame> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &Frame_msg;
    }
};
template <>
struct MessageDescriptor<InputEvent> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &InputEvent_msg;
    }
};
template <>
struct MessageDescriptor<ClientPacket> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &ClientPacket_msg;
    }
};
template <>
struct MessageDescriptor<ClientInfo> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 5;
    static inline const pb_msgdesc_t* fields() {
        return &ClientInfo_msg;
    }
};
template <>
struct MessageDescriptor<RemoteLog> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 1;
    static inline const pb_msgdesc_t* fields() {
        return &RemoteLog_msg;
    }
};
}  // namespace nanopb

#endif  /* __cplusplus */


#endif
