/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(Frame, Frame, 2)


PB_BIND(WFrame, WFrame, 2)


PB_BIND(RGBFrame, RGBFrame, 2)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(FirmwareConfig, FirmwareConfig, AUTO)


PB_BIND(FirmwarePacket, FirmwarePacket, AUTO)


PB_BIND(FirmwareInfo, FirmwareInfo, AUTO)


PB_BIND(RemoteLog, RemoteLog, AUTO)





