import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :octopus, OctopusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  check_origin: false

config :octopus,
  broadcast: true,
  show_sim_preview: false,
  broadcast_ip: {192, 168, 1, 255}

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Octopus.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
